### ISSUE TITLE
Trace offset

### ISSUE THREAD

**Issue by wjxiong** [opengeostat/pygslib#1]
In some cases, drill hole trace created with the desurvey method in pygslib does not align well with the trace created in other tools. Attached screenshot is an example of such offset between pygslib(yellow) and GEMS(cyan). 
![offset](https://cloud.githubusercontent.com/assets/22301695/18641721/cd4289e4-7e6b-11e6-894f-b4b293efa679.png)

**Comment by opengeostat** [comment]
wjxiong, 

Thank you for reporting this issue. 

This was a rounding error and it was fixed by redefining float variables to double (see pygslib/cython_code/drillhole.pyx, lines 1655 to 1666,  commit 225209ced44965833fe0ed8a23b3765d2fc1969f). 

Please note that in the process of finding the bug the desurvey function was rewritten.  

Please download the last version of PyGSLIB, try again and let me know if the error persists with your data. I did my own test with proprietary data desurveyed with Datamine Studio and it works. 

Kind regards 
Adrian

**Comment by wjxiong** [comment]
I just tested desurveying function in the latest pygslib. The drillholes are now well matched with the dxf traces. 
Thank you.

**Comment by opengeostat** [comment]
Hi wjxiong, 

[ramaguirre](https://github.com/ramaguirre)  identified an issue  with the code. The algorithm for desurvey uses survey calculated in previous table interval instead of using measured survey intervals for all calculations. The actual code returns different coordinate results for tables with different interval sequence:

 
![error in survey](https://user-images.githubusercontent.com/14026093/44224195-bd013600-a157-11e8-8d71-b52eb7af09f9.png)

This is the code generated by [ramaguirre](https://github.com/ramaguirre) (with some minor changes)


``` python

# coding: utf-8

# In[1]:


import pandas as pd
import matplotlib.pylab as plt
import pygslib
import numpy as np


# In[2]:


#Test collar table
collar=pd.DataFrame().append(dict(zip([u'BHID', u'XCOLLAR', u'YCOLLAR', u'ZCOLLAR', u'LENGTH'],['SRVTST',0,0,0,261.25])),ignore_index=True)


# In[3]:


#Test Survey Table
survey=pd.DataFrame(dict(zip(['BHID','AT','AZ','DIP'],[['SRVTST']*5,
[0.0, 15.0, 45.0, 75.0, 105.0],
[0.0, 317.1, 356.1, 10.9, 287.1],
[90.0, 88.7, 85.9, 82.9, 78.8]])))


# In[4]:


#Test Interval Table
frm=[]
to=[]
val=[]
count=1
for i in range (0,262,2):
    frm.append(i)
    to.append(i+2)
    val.append(count)
    count+=1

samps=pd.DataFrame(dict(zip(['BHID','FROM','TO','VALUE'],[['SRVTST']*len(frm),frm,to,count])))


# In[5]:


db=pygslib.drillhole.Drillhole(collar=collar, survey=survey)
fig=plt.figure(figsize=(12, 12), dpi=80)
ax=plt.subplot()

for i in [0,85,100]:
    name='samps_'+str(i)
    db.addtable(samps[samps.FROM>=i],name,overwrite=True)
    db.add_gaps(name, name, overwrite=True)
    db.desurvey(name,endpoints=True)
    ax.scatter(db.table[name].xm,db.table[name].ym,marker='+',alpha=0.8,label=name)

ax.set_title('Plan View')
ax.set_xlim(-50,50)
ax.set_ylim(-50,50)
plt.legend()
plt.show()


# In[6]:


db.table_mames


# In[7]:


db=pygslib.drillhole.Drillhole(collar=collar, survey=survey)
fig=plt.figure(figsize=(12, 12), dpi=80)
ax=plt.subplot()
for i in [0,85,100]:
    name='samps_'+str(i)
    db.addtable(samps[samps.FROM>=i],name,overwrite=True)
    db.desurvey(name,endpoints=True)
    #db.table[name].to_csv(name+'.csv')
    ax.scatter(db.table[name].xm,db.table[name].zm,marker='+',alpha=0.8,label=name)
ax.set_title('Profile View')
ax.set_ylim(-280,20)
ax.set_xlim(150,-150)
plt.legend()
plt.show()


```

**Comment by opengeostat** [comment]
The function Drillhole.desurvey is now deprecated. Use Drillhole.desurvey_table
