### ISSUE TITLE
Issue with number of downhole composites

### ISSUE THREAD

**Issue by ramaguirre** [opengeostat/pygslib#11]
Problema: queda 'colas' sin compositar al final de un sondaje, cuando el largo de la cola es menor a la mitad del largo del compósito.

Creo que esto se produce porque la función 'int' redondea hacia abajo y al iterar sobre ncomp el último valor del rango no es incluido

Drillhole.pyx 

593: ncomp = int(ito[-1]/cint + 1)  # number of composites

624:    # for each composite 
625:   for i in range (ncomp): 

![image](https://user-images.githubusercontent.com/28491587/43611839-73bfe002-9678-11e8-8068-0a14a047d376.png)

**Comment by opengeostat** [comment]
Ramon, 
I think this may not be an error, the interval is not saved if the minimum length condition (`minlen`) is not satisfied. For example, in the code 
```
mydholedb.downh_composite('assay', variable_name= "CU", new_table_name= "CMP", 
                          cint = 100, minlen=-1, overwrite = True)

``` 
`minlen = 50` because `minlen = cint/2 if minlen < 0`

Use a small `minlen` value, for example, 

```
mydholedb.downh_composite('assay', variable_name= "CU", new_table_name= "CMP", 
                          cint = 100, minlen=0.01, overwrite = True)

``` 
give you this: 

![image](https://user-images.githubusercontent.com/14026093/43616165-2bd6ffbc-9689-11e8-86cb-9748c95a0a46.png)

Note that PuGSLIB always creates the whole From-To interval, but you can identify these using the property `_len`. 

I may update the code to `int(ceil(ito[-1]/cint + 1))` this will give at least one extra interval but results may be wrong if  `minlen==0`

**Comment by ramaguirre** [comment]
Adrián,

I checked and you are correct. The error was due to the software I was using to display the hole (Leapfrog Geo). Since the las composite exceeded the drillhole length, it wouldn't display it. Sorry about that, and thanks for the answer.

Ramón.

2018-08-02 19:26 GMT-04:00 Adrian Martinez Vargas <notifications@github.com<mailto:notifications@github.com>>:

Ramon,
I think this may not be an error, the interval is not saved if the minimum length condition (minlen) is not satisfied. For example, in the code

mydholedb.downh_composite('assay', variable_name= "CU", new_table_name= "CMP",
                          cint = 100, minlen=-1, overwrite = True)



minlen = 50 because minlen = cint/2 if minlen < 0

Use a small minlen value, for example,

mydholedb.downh_composite('assay', variable_name= "CU", new_table_name= "CMP",
                          cint = 100, minlen=0.01, overwrite = True)



give you this:

[image]<https://user-images.githubusercontent.com/14026093/43616165-2bd6ffbc-9689-11e8-86cb-9748c95a0a46.png>

Note that PuGSLIB always creates the whole From-To interval, but you can identify these using the property _len.

I may update the code to int(ceil(ito[-1]/cint + 1)) this will give at least one extra interval but results may be wrong if minlen==0

**Comment by opengeostat** [comment]
Ramón, 

Thank you for testing and contributing to PyGSLIB. 

Kind regards, 
Adrian Martinez Vargas
